version: "3.7"

services:
  mc:
    countainer_name: mc
    image: itzg/minecraft-server:1.19.2
    # restart: unless-stopped
    volumes:
      # use a named, managed volume for data volume
      - ./server:/data
      # attach local host directory "mods" in same directory as this compose file
      # all mods in this directory get copied into /data/mods at startup
      - ./mods:/mods:ro
    env_file: .env
    ports:
      # expose the Minecraft server port outside of container
      - 25565:25565
